version: "3.8"

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: miniShop
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3366:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
